[project]
name = "chaucherapp-backend"
version = "0.1.0"
description = "Backend FastAPI para la priorización de tickets de ChaucherApp"
requires-python = ">=3.12"
dependencies = [
    "fastapi",
    "uvicorn[standard]",
    "python-dotenv",
    "langchain-google-genai",
    "cloudpickle==3.1.2",
    "pandas==2.3.3",
    "scikit-learn==1.8.0",
    "numpy==2.4.3",
    "nltk",
]
